### ISSUE TITLE
feat(v1): CLI usage

### ISSUE THREAD

**Issue by aosasona** [aosasona/migrant#7]
Currently, migrations can only be run in code, which isn't really ideal to run it every-time you start your app, not because it isn't safe but it simply doesn't need to be. In V1, we could have a way to do `gleam run -m migrant migrate|revert|new...` and set the configuration options in the `gleam.toml` file under the migrant table like this:

```toml
[migrant]
driver = "sqlite"
db_path = "./data.db"
# or even better with environment variables
# db_path = "{{ env.DB_PATH }} " # or just "{{ .DB_PATH }}"?
```

> [!NOTE]
> The main issue with this will be the inability to use drivers that are not built in to migrant itself, those would still have to be accessed in code until I choose to directly support another driver like "pgo" (holding off on that for now).
